### ISSUE TITLE
Error when populating localizations

### ISSUE THREAD

**Issue by mike85** [mattmilburn/strapi-plugin-permalinks#32]
When requesting pages with localizations (e.g. `/api/pages?populate=localizations`), I get the following error:

```javascript
error: data.localizations.map is not a function
TypeError: data.localizations.map is not a function
    at transform (/node_modules/strapi-plugin-permalinks/server/middlewares/transform-api-response.js:48:47)
    at transform (/node_modules/strapi-plugin-permalinks/server/middlewares/transform-api-response.js:33:14)
    at /node_modules/strapi-plugin-permalinks/server/middlewares/transform-api-response.js:41:34
    at Array.map (<anonymous>)
    at transform (/node_modules/strapi-plugin-permalinks/server/middlewares/transform-api-response.js:41:21)
    at /node_modules/strapi-plugin-permalinks/server/middlewares/transform-api-response.js:90:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
    at async /node_modules/@strapi/strapi/lib/middlewares/logger.js:9:5
    at async /node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
``` 

This should fix the issue:
```javascript
if ( has( data, 'localizations' ) ) {
      data.localizations.data = data.localizations.data.map( entry => transform( entry, uid, config ) );
}
``` 

Strapi-Version: 4.8.2
Plugin-Version: 1.0.3

**Comment by kwame-dat** [comment]
We are having the same issue. Please would it possible to action this for us? I can create a PR if need

**Comment by mattmilburn** [comment]
Hi @mike85 @kwame-dat, a new [version 1.0.4](https://github.com/mattmilburn/strapi-plugin-permalinks/releases/tag/v1.0.4) of this plugin was released that has a fix for this issue. Sorry for the trouble! Let me know how it goes for you 🙂

**Comment by mike85** [comment]
Awesome, thanks! I hope I can test it soon. 🤩
